### ISSUE TITLE
Maybe a bug?

### ISSUE THREAD

**Issue by xbcdbc** [dlr1516/grd#3]
I find that line 222 in functions.cpp,the formula of g0 is inconsistent with the formula （14）that in your paper.

**Comment by dlr1516** [comment]
Well, I think you refer to line 221:

double g0 = sqrt(0.5 * M_PI) * (1.0 - std::erf(ratio / sqrt(2.0)));

whereas from (14) in the paper it should be 

double g0 = sqrt(0.5 * M_PI) * (1.0 + std::erf(ratio / sqrt(2.0)));

I have to check my notes before properly answering. I thank you for your check.
